default: &default
  adapter: mysql2
  encoding: utf8
  database: cpositivo
  username: b15ccbb231c891
  password: 99f47739
  host: us-cdbr-azure-east-c.cloudapp.net
  port: 3306

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default